spring:
  mvc:
    view:
      prefix: /WEB-INF/ 
      suffix: .jsp
  http:
    multipart:
      enabled: true
    encoding:
      charset: utf-8
      enabled: true
      force: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shiro?characterEncoding=UTF-8  
    username: root
    password: "000000"
server:
  address: 127.0.0.1
  port: 80
mybatis:
  mapper-locations: classpath:com/topscit/springboot1/mapper/*.xml

