spring:
  mvc:
    view:
      prefix: /WEB-INF/ 
      suffix: .jsp
  http:
    multipart:
      enabled: true
    encoding:
      charset: utf-8
      enabled: true
      force: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shiro?characterEncoding=UTF-8  
<<<<<<< HEAD
    username: root
    password: root

=======
    username: root
    password: "root"
 
>>>>>>> branch 'master' of https://github.com/wwj0622/CRM.git
server:
  address: 127.0.0.1
  port: 80
mybatis:
  mapper-locations: classpath:com/topscit/springboot1/mapper/*.xml

